import type { PropVariant } from "../placements";
import type { PropBuilder } from "./context";
import {
  buildBell,
  buildBookRow,
  buildBookStack,
  buildBust,
  buildClamp,
  buildDisplayStand,
  buildGlobe,
  buildHandTool,
  buildIndicatorLight,
  buildLongcaseClock,
  buildMannequin,
  buildMantelClock,
  buildOrnament,
  buildParcel,
  buildPictureFrame,
  buildPlant,
  buildRegister,
  buildRoll,
  buildSpecimenJar,
  buildStorageBox,
  buildVessel,
  buildWallClock,
} from "./decor";
import {
  buildArmchair,
  buildBackCabinet,
  buildCounter,
  buildCrate,
  buildCurtain,
  buildDisplayCabinet,
  buildDisplayTray,
  buildFootstool,
  buildHangingSign,
  buildLadder,
  buildLadderbackChair,
  buildLowShelf,
  buildMonitorDesk,
  buildPlinth,
  buildRug,
  buildShelvingUnit,
  buildSideTable,
  buildStool,
  buildUmbrellaStand,
  buildWallShelf,
  buildWorkbench,
} from "./furniture";
import {
  buildCandlestick,
  buildFloorLamp,
  buildPendantLamp,
  buildTableLamp,
  buildTaskLight,
  buildWallSconce,
} from "./lamps";

/** Every authored variant, resolved to the builder that realises it. */
export const PROP_BUILDERS: Readonly<Record<PropVariant, PropBuilder>> = {
  floor_lamp: buildFloorLamp,
  table_lamp: buildTableLamp,
  wall_sconce: buildWallSconce,
  pendant_lamp: buildPendantLamp,
  task_light: buildTaskLight,
  candlestick: buildCandlestick,

  armchair: buildArmchair,
  footstool: buildFootstool,
  stool: buildStool,
  ladderback_chair: buildLadderbackChair,
  side_table: buildSideTable,
  plinth: buildPlinth,
  display_cabinet: buildDisplayCabinet,
  wall_shelf: buildWallShelf,
  low_shelf: buildLowShelf,
  shelving_unit: buildShelvingUnit,
  counter: buildCounter,
  back_cabinet: buildBackCabinet,
  workbench: buildWorkbench,
  crate: buildCrate,
  umbrella_stand: buildUmbrellaStand,
  rug: buildRug,
  ladder: buildLadder,
  curtain: buildCurtain,
  hanging_sign: buildHangingSign,
  display_tray: buildDisplayTray,
  monitor_desk: buildMonitorDesk,

  vase_tall: buildVessel,
  vase_round: buildVessel,
  bottle: buildVessel,
  urn: buildVessel,
  bowl: buildVessel,
  teapot: buildVessel,
  kettle: buildVessel,
  book_stack: buildBookStack,
  book_row: buildBookRow,
  parcel: buildParcel,
  storage_box: buildStorageBox,
  picture_frame: buildPictureFrame,
  wall_clock: buildWallClock,
  mantel_clock: buildMantelClock,
  longcase_clock: buildLongcaseClock,
  bust: buildBust,
  mannequin: buildMannequin,
  plant: buildPlant,
  register: buildRegister,
  bell: buildBell,
  paper_roll: buildRoll,
  fabric_roll: buildRoll,
  hand_tool: buildHandTool,
  clamp: buildClamp,
  globe: buildGlobe,
  display_stand: buildDisplayStand,
  ornament: buildOrnament,
  specimen_jar: buildSpecimenJar,
  indicator_light: buildIndicatorLight,
};

export { buildArchitecture, OFFICE_DOOR_NAME, OFFICE_STAFF_BARRIER_NAME } from "./architecture";
export type { PropBuilder, PropContext } from "./context";
